// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using sol_Job_Bank.Data;

namespace sol_Job_Bank.Data.JBMigrations
{
    [DbContext(typeof(JobBankContext))]
    partial class JobBankContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("JB")
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079");

            modelBuilder.Entity("sol_Job_Bank.Models.Applicant", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(256);

                    b.Property<DateTime?>("CreatedOn");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("MiddleName")
                        .HasMaxLength(30);

                    b.Property<long>("Phone");

                    b.Property<int?>("RetrainingProgramID");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate();

                    b.Property<string>("SIN")
                        .IsRequired()
                        .HasMaxLength(9);

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(256);

                    b.Property<DateTime?>("UpdatedOn");

                    b.Property<string>("eMail")
                        .IsRequired()
                        .HasMaxLength(255);

                    b.HasKey("ID");

                    b.HasIndex("RetrainingProgramID");

                    b.HasIndex("eMail")
                        .IsUnique()
                        .HasName("IX_Unique_Applicant_email");

                    b.ToTable("Applicants");
                });

            modelBuilder.Entity("sol_Job_Bank.Models.ApplicantSkill", b =>
                {
                    b.Property<int>("ApplicantID");

                    b.Property<int>("SkillID");

                    b.HasKey("ApplicantID", "SkillID");

                    b.HasIndex("SkillID");

                    b.ToTable("ApplicantSkills");
                });

            modelBuilder.Entity("sol_Job_Bank.Models.Application", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("ApplicantID");

                    b.Property<string>("Comments")
                        .IsRequired()
                        .HasMaxLength(2000);

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(256);

                    b.Property<DateTime?>("CreatedOn");

                    b.Property<int>("PostingID");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(256);

                    b.Property<DateTime?>("UpdatedOn");

                    b.HasKey("ID");

                    b.HasIndex("PostingID");

                    b.HasIndex("ApplicantID", "PostingID")
                        .IsUnique()
                        .HasName("IX_Unique_Application");

                    b.ToTable("Applications");
                });

            modelBuilder.Entity("sol_Job_Bank.Models.FileContent", b =>
                {
                    b.Property<int>("FileContentID");

                    b.Property<byte[]>("Content");

                    b.HasKey("FileContentID");

                    b.ToTable("FileContent");
                });

            modelBuilder.Entity("sol_Job_Bank.Models.Occupation", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(256);

                    b.Property<DateTime?>("CreatedOn");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(256);

                    b.Property<DateTime?>("UpdatedOn");

                    b.HasKey("ID");

                    b.ToTable("Occupations");
                });

            modelBuilder.Entity("sol_Job_Bank.Models.PhotoContent", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<byte[]>("Content");

                    b.Property<string>("MimeType")
                        .HasMaxLength(255);

                    b.Property<int?>("PhotoFullId");

                    b.Property<int?>("PhotoThumbId");

                    b.HasKey("ID");

                    b.HasIndex("PhotoFullId")
                        .IsUnique();

                    b.HasIndex("PhotoThumbId")
                        .IsUnique();

                    b.ToTable("PhotoContent");
                });

            modelBuilder.Entity("sol_Job_Bank.Models.Position", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(256);

                    b.Property<DateTime?>("CreatedOn");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(2000);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255);

                    b.Property<int>("OccupationID");

                    b.Property<decimal>("Salary")
                        .HasColumnType("decimal(9,2)");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(256);

                    b.Property<DateTime?>("UpdatedOn");

                    b.HasKey("ID");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("OccupationID");

                    b.ToTable("Positions");
                });

            modelBuilder.Entity("sol_Job_Bank.Models.PositionSkill", b =>
                {
                    b.Property<int>("PositionID");

                    b.Property<int>("SkillID");

                    b.HasKey("PositionID", "SkillID");

                    b.HasIndex("SkillID");

                    b.ToTable("PositionSkills");
                });

            modelBuilder.Entity("sol_Job_Bank.Models.Posting", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("ClosingDate");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(256);

                    b.Property<DateTime?>("CreatedOn");

                    b.Property<int>("NumberOpen");

                    b.Property<int>("PositionID");

                    b.Property<DateTime?>("StartDate");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(256);

                    b.Property<DateTime?>("UpdatedOn");

                    b.HasKey("ID");

                    b.HasIndex("PositionID", "ClosingDate")
                        .IsUnique();

                    b.ToTable("Postings");
                });

            modelBuilder.Entity("sol_Job_Bank.Models.RetrainingProgram", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(256);

                    b.Property<DateTime?>("CreatedOn");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(70);

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(256);

                    b.Property<DateTime?>("UpdatedOn");

                    b.HasKey("ID");

                    b.ToTable("RetrainingPrograms");
                });

            modelBuilder.Entity("sol_Job_Bank.Models.Skill", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(256);

                    b.Property<DateTime?>("CreatedOn");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(256);

                    b.Property<DateTime?>("UpdatedOn");

                    b.HasKey("ID");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Skills");
                });

            modelBuilder.Entity("sol_Job_Bank.Models.UploadedFile", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Description")
                        .HasMaxLength(2000);

                    b.Property<string>("Discriminator")
                        .IsRequired();

                    b.Property<string>("FileName")
                        .HasMaxLength(255);

                    b.Property<string>("MimeType")
                        .HasMaxLength(255);

                    b.HasKey("ID");

                    b.ToTable("UploadedFiles");

                    b.HasDiscriminator<string>("Discriminator").HasValue("UploadedFile");
                });

            modelBuilder.Entity("sol_Job_Bank.Models.UploadedPhoto", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Discriminator")
                        .IsRequired();

                    b.Property<string>("FileName")
                        .HasMaxLength(255);

                    b.HasKey("ID");

                    b.ToTable("UploadedPhotos");

                    b.HasDiscriminator<string>("Discriminator").HasValue("UploadedPhoto");
                });

            modelBuilder.Entity("sol_Job_Bank.Models.ApplicantDocument", b =>
                {
                    b.HasBaseType("sol_Job_Bank.Models.UploadedFile");

                    b.Property<int>("ApplicantID");

                    b.HasIndex("ApplicantID");

                    b.HasDiscriminator().HasValue("ApplicantDocument");
                });

            modelBuilder.Entity("sol_Job_Bank.Models.PostingDocument", b =>
                {
                    b.HasBaseType("sol_Job_Bank.Models.UploadedFile");

                    b.Property<int>("PostingID");

                    b.HasIndex("PostingID");

                    b.HasDiscriminator().HasValue("PostingDocument");
                });

            modelBuilder.Entity("sol_Job_Bank.Models.ApplicantPhoto", b =>
                {
                    b.HasBaseType("sol_Job_Bank.Models.UploadedPhoto");

                    b.Property<int>("ApplicantID");

                    b.HasIndex("ApplicantID")
                        .IsUnique();

                    b.HasDiscriminator().HasValue("ApplicantPhoto");
                });

            modelBuilder.Entity("sol_Job_Bank.Models.Applicant", b =>
                {
                    b.HasOne("sol_Job_Bank.Models.RetrainingProgram", "RetrainingProgram")
                        .WithMany("Applicants")
                        .HasForeignKey("RetrainingProgramID");
                });

            modelBuilder.Entity("sol_Job_Bank.Models.ApplicantSkill", b =>
                {
                    b.HasOne("sol_Job_Bank.Models.Applicant", "Applicant")
                        .WithMany("ApplicantSkills")
                        .HasForeignKey("ApplicantID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("sol_Job_Bank.Models.Skill", "Skill")
                        .WithMany("ApplicantSkills")
                        .HasForeignKey("SkillID")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("sol_Job_Bank.Models.Application", b =>
                {
                    b.HasOne("sol_Job_Bank.Models.Applicant", "Applicant")
                        .WithMany("Applications")
                        .HasForeignKey("ApplicantID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("sol_Job_Bank.Models.Posting", "Posting")
                        .WithMany("Applications")
                        .HasForeignKey("PostingID")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("sol_Job_Bank.Models.FileContent", b =>
                {
                    b.HasOne("sol_Job_Bank.Models.UploadedFile", "UploadedFile")
                        .WithOne("FileContent")
                        .HasForeignKey("sol_Job_Bank.Models.FileContent", "FileContentID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("sol_Job_Bank.Models.PhotoContent", b =>
                {
                    b.HasOne("sol_Job_Bank.Models.UploadedPhoto", "PhotoFull")
                        .WithOne("PhotoContentFull")
                        .HasForeignKey("sol_Job_Bank.Models.PhotoContent", "PhotoFullId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("sol_Job_Bank.Models.UploadedPhoto", "PhotoThumb")
                        .WithOne("PhotoContentThumb")
                        .HasForeignKey("sol_Job_Bank.Models.PhotoContent", "PhotoThumbId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("sol_Job_Bank.Models.Position", b =>
                {
                    b.HasOne("sol_Job_Bank.Models.Occupation", "Occupation")
                        .WithMany("Positions")
                        .HasForeignKey("OccupationID")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("sol_Job_Bank.Models.PositionSkill", b =>
                {
                    b.HasOne("sol_Job_Bank.Models.Position", "Position")
                        .WithMany("PositionSkills")
                        .HasForeignKey("PositionID")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("sol_Job_Bank.Models.Skill", "Skill")
                        .WithMany("PositionSkills")
                        .HasForeignKey("SkillID")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("sol_Job_Bank.Models.Posting", b =>
                {
                    b.HasOne("sol_Job_Bank.Models.Position", "Position")
                        .WithMany("Postings")
                        .HasForeignKey("PositionID")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("sol_Job_Bank.Models.ApplicantDocument", b =>
                {
                    b.HasOne("sol_Job_Bank.Models.Applicant", "Applicant")
                        .WithMany("ApplicantDocuments")
                        .HasForeignKey("ApplicantID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("sol_Job_Bank.Models.PostingDocument", b =>
                {
                    b.HasOne("sol_Job_Bank.Models.Posting", "Posting")
                        .WithMany("PostingDocuments")
                        .HasForeignKey("PostingID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("sol_Job_Bank.Models.ApplicantPhoto", b =>
                {
                    b.HasOne("sol_Job_Bank.Models.Applicant", "Applicant")
                        .WithOne("ApplicantPhoto")
                        .HasForeignKey("sol_Job_Bank.Models.ApplicantPhoto", "ApplicantID")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
